name: pokemobile
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  equatable: ^2.0.3
  flutter_bloc: ^7.1.0
  flutter_launcher_icons: ^0.9.1
  flutter_spinkit: ^5.0.0
  get_it: ^7.2.0
  graphql_flutter: ^5.0.0
  pagination_view: ^2.0.0
  shared_preferences: ^2.0.6
  splashscreen: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.13

flutter_icons:
  image_path: "assets/images/logo_splash.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: PokemonElementIcon
      fonts:
        - asset: assets/icons/PokemonElementIcon.ttf
    - family: PokedexUiIcon
      fonts:
        - asset: assets/icons/PokedexUiIcon.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
